# University Policies

## Academic Integrity Code

Academic integrity is an essential part of the educational process, and all members of the GW community take these matters very seriously. As the instructor of record for this course, my role is to provide clear expectations and uphold them in all assessments. Violations of academic integrity occur when students fail to cite research sources properly, engage in unauthorized collaboration, falsify data, and otherwise violate the Code of Academic Integrity. If you have any questions about whether particular academic practices or resources are permitted, you should ask me for clarification. If you are reported for an academic integrity violation, you should contact Conflict Education and Student Accountability (CESA), formerly known as Student Rights and Responsibilities (SRR), to learn more about your rights and options in the process. Consequences can range from failure of assignment to expulsion from the University and may include a transcript notation. For more information, refer to the CESA website at [students.gwu.edu/code-academic-integrity](https://students.gwu.edu/code-academic-integrity) or contact CESA by email ([cesa@gwu.edu](mailto:cesa@gwu.edu)) or phone (202-994-6757).

## Observance of Religious Holidays

Students must notify faculty during the first week of the semester in which they are enrolled in the course, or as early as possible, but no later than three weeks prior to the absence, of their intention to be absent from class on their day(s) of religious observance. If the holiday falls within the first three weeks of class, the student must inform faculty in the first week of the semester. For details and policy, see [provost.gwu.edu/policies-procedures-and-guidelines](https://provost.gwu.edu/policies-procedures-and-guidelines).

## Use of Electronic Course Materials and Class Recordings

Students are encouraged to use electronic course materials, including recorded class sessions, for private personal use in connection with their academic program of study. Electronic course materials and recorded class sessions should not be shared or used for non-course related purposes unless express permission has been granted by the instructor. Students who impermissibly share any electronic course materials are subject to discipline under the Student Code of Conduct. Contact the instructor if you have questions regarding what constitutes permissible or impermissible use of electronic course materials and/or recorded class sessions. Contact Disability Support Services at [disabilitysupport.gwu.edu](https://disabilitysupport.gwu.edu) if you have questions or need assistance in accessing electronic course materials.

## Academic Support

**Academic Commons.** Academic Commons is the central location for academic support resources for GW students. To schedule a peer tutoring session for a variety of courses visit [go.gwu.edu/tutoring](https://go.gwu.edu/tutoring). Visit [academiccommons.gwu.edu](https://academiccommons.gwu.edu) for study skills tips, finding help with research, and connecting with other campus resources. For questions email [academiccommons@gwu.edu](mailto:academiccommons@gwu.edu).

**GW Writing Center.** GW Writing Center cultivates confident writers in the University community by facilitating collaborative, critical, and inclusive conversations at all stages of the writing process. Working alongside peer mentors, writers develop strategies to write independently in academic and public settings. Appointments can be booked online at [gwu.mywconline](https://gwu.mywconline.com).

## Support for Students In and Outside the Classroom

**Disability Support Services (DSS), 202-994-8250.** Any student who may need an accommodation based on the potential impact of a disability should contact Disability Support Services at [disabilitysupport.gwu.edu](https://disabilitysupport.gwu.edu) to establish eligibility and to coordinate reasonable accommodations.

**Student Health Center, 202-994-5300, 24/7.** The Student Health Center (SHC) offers medical, counseling/psychological, and psychiatric services to GW students. More information about the SHC is available at [healthcenter.gwu.edu](https://healthcenter.gwu.edu). Students experiencing a medical or mental health emergency on campus should contact GW Emergency Services at 202-994-6111, or off campus at 911.

## GW Campus Emergency Information

GW Emergency Services: 202-994-6111. For situation-specific instructions, refer to GW's Emergency Procedures guide.

**GW Alert.** GW Alert is an emergency notification system that sends alerts to the GW community. GW requests students, faculty, and staff maintain current contact information by logging on to [alert.gwu.edu](https://alert.gwu.edu). Alerts are sent via email, text, social media, and other means, including the Guardian app. The Guardian app is a safety app that allows you to communicate quickly with GW Emergency Services, 911, and other resources. Learn more at [safety.gwu.edu](https://safety.gwu.edu).

**Protective Actions.** GW prescribes four protective actions that can be issued by university officials depending on the type of emergency. All GW community members are expected to follow directions according to the specified protective action. The protective actions are Shelter, Evacuate, Secure, and Lockdown (details below). Learn more at [safety.gwu.edu/gw-standard-emergency-statuses](https://safety.gwu.edu/gw-standard-emergency-statuses).

- **Shelter:** Protection from a specific hazard. The hazard could be a tornado, earthquake, hazardous material spill, or other environmental emergency. Specific safety guidance will be shared on a case-by-case basis.
  - *Action:* Follow safety guidance for the hazard.
- **Evacuate:** Need to move people from one location to another. Students and staff should be prepared to follow specific instructions given by first responders and University officials.
  - *Action:* Evacuate to a designated location. Leave belongings behind. Follow additional instructions from first responders.
- **Secure:** Threat or hazard outside of buildings or around campus. Increased security, secured building perimeter, increased situational awareness, and restricted access to entry doors.
  - *Action:* Go inside and stay inside. Activities inside may continue.
- **Lockdown:** Threat or hazard with the potential to impact individuals inside buildings. Room-based protocol that requires locking interior doors, turning off lights, and staying out of sight of corridor windows.
  - *Action:* Locks, lights, out of sight. Consider Run, Hide, Fight.

**Classroom emergency lockdown buttons.** Some classrooms have been equipped with classroom emergency lockdown buttons. If the button is pushed, GWorld Card access to the room will be disabled, and GW Dispatch will be alerted. The door must be manually closed if it is not closed when the button is pushed. Anyone in the classroom will be able to exit, but no one will be able to get in.
